// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #HelmReleaseStep is the `step:helm-release` install step's plugin_input: the
// helm upgrade --install invocation the step performs IN-VENUE (against the venue's
// kubeconfig — /etc/rancher/k3s/k3s.yaml on a k3s guest). Field set confirmed by the
// Unit 1 schema spike.
type HelmReleaseStep struct {
	// repo — the chart repository URL (helm repo add + --repo). Optional: a chart may
	// come from a pre-added repo or an OCI reference.
	Repo string `yaml:"repo,omitempty" json:"repo,omitempty"`

	// chart — the chart name (required). May be a bare name (resolved via repo) or a
	// full reference.
	Chart string `yaml:"chart,omitempty" json:"chart"`

	// version — the chart version to pin (helm upgrade --install --version).
	Version string `yaml:"version,omitempty" json:"version,omitempty"`

	// release — the release name (required).
	Release string `yaml:"release,omitempty" json:"release"`

	// namespace — the target namespace (helm --namespace; created if absent).
	Namespace string `yaml:"namespace,omitempty" json:"namespace,omitempty"`

	// values — inline values (helm --set key=value per leaf, or a values map).
	Values map[string]any/* CUE top */ `yaml:"values,omitempty" json:"values,omitempty"`

	// values_files — values YAML files (helm -f), venue-relative paths.
	Values_files []string `yaml:"values_files,omitempty" json:"values_files,omitempty"`

	// wait — wait for the release to become ready (helm --wait).
	Wait bool `yaml:"wait,omitempty" json:"wait,omitempty"`

	// timeout — the wait timeout (helm --timeout, e.g. "5m").
	Timeout string `yaml:"timeout,omitempty" json:"timeout,omitempty"`
}

// #HelmInput is the `verb:helm` check verb's plugin_input: the method name plus its
// method-exclusive modifiers. The verb's PRIMARY input field is `method`, so
// `helm: release-exists` desugars to {method: "release-exists"}.
type HelmInput struct {
	// method — the helm assertion method.
	Method string `yaml:"method,omitempty" json:"method"`

	// release — the release name to assert on (required).
	Release string `yaml:"release,omitempty" json:"release"`

	// namespace — the release's namespace (default "default").
	Namespace string `yaml:"namespace,omitempty" json:"namespace,omitempty"`

	// status — method:status — the expected release status (default "deployed").
	Status string `yaml:"status,omitempty" json:"status,omitempty"`

	// revision — method:revision — the minimum release revision to assert (≥).
	Revision int64 `yaml:"revision,omitempty" json:"revision,omitempty"`

	// values_hash — method:values-hash — the expected SHA-256 of the release's
	// rendered values (helm get values -o json | sha256sum).
	Values_hash string `yaml:"values_hash,omitempty" json:"values_hash,omitempty"`
}
